name: text_recognition_flutter
description: A sample Flutter project that use text recognition.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  http: ^0.13.5
  google_mlkit_text_recognition: ^0.4.0
  permission_handler: ^10.2.0
  #텍스트를 감지 할 수 있는 googleapis
  #카메라를 열 수 있는 권한을 요청할 수 있는 permission_handler
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true